without styles and button
Anastasiya-Shir/AplicationReact pull request #1
Opened 2022-07-03 19:02 UTC by Anastasiya-Shir

2022-07-04 21:47 UTC, kathrynowy requested changes

2022-07-04 21:47 UTC, kathrynowy commented on src/App.css
> +.App {
why it starts with a capital letter?

2022-07-04 21:47 UTC, kathrynowy commented on src/App.css
> +}
```suggestion
.logo{
  width: 50px;
} 
```

2022-07-04 21:47 UTC, kathrynowy commented on src/App.css
> +  padding:3% 10%;
```suggestion
  padding: 3% 10%;
```

2022-07-04 21:47 UTC, kathrynowy commented on src/App.css
> + .header{
```suggestion
 .header {
```

2022-07-04 21:47 UTC, kathrynowy commented on src/App.css
> +  background-color: aqua;
hex

2022-07-04 21:47 UTC, kathrynowy commented on src/App.css
> + }
исправить везде отступы И так далее

2022-07-04 21:47 UTC, kathrynowy commented on src/App.css
> + .filmCard a{
movie

2022-07-04 21:47 UTC, kathrynowy commented on src/App.css
> +  background-color:aquamarine;
move to scss file colors and use variables + hex

2022-07-04 21:47 UTC, kathrynowy commented on src/App.css
> +  margin: 0.40px;
0.40?

2022-07-04 21:47 UTC, kathrynowy commented on src/App.css
> +  margin: 0.40px;
we don't use floating numbers

2022-07-04 21:47 UTC, kathrynowy commented on src/App.js
> +import { BrowserRouter as Router, Routes, Route, } from 'react-router-dom';
```suggestion
import React from 'react';
import { BrowserRouter as Router, Routes, Route, } from 'react-router-dom';

import Header from './components/Header';
import Films from './components/Films';
import Dicription from './components/Disription';

import './App.css';
```

2022-07-04 21:47 UTC, kathrynowy commented on src/App.js
> +        <Header />
что та пустые строки после открытия тэга?

2022-07-04 21:47 UTC, kathrynowy commented on src/App.js
> +
тоже убрать

2022-07-04 21:47 UTC, kathrynowy commented on src/App.js
> +          <Route exact path="/" element={<Films />} />
Movies

2022-07-04 21:47 UTC, kathrynowy commented on src/App.js
> +      <div className="App">
do you need this div?

2022-07-04 21:47 UTC, kathrynowy commented on src/App.js
> +          <Route path="/movie-description/:eventId" element={<Dicription />} /></Routes>
```suggestion
          <Route path="/movie-description/:eventId" element={<Dicription />} />
          </Routes>
```

2022-07-04 21:47 UTC, kathrynowy commented on src/components/Movie.jsx
> +
remove empty line everywhere in this place, described in the group

2022-07-04 21:47 UTC, kathrynowy commented on src/components/Movie.jsx
> +      <div className="filmCard" >
movie

2022-07-04 21:47 UTC, kathrynowy commented on src/components/Movie.jsx
> +        <img src={item.posterLink} alt="movie"></img>
```suggestion
        <img src={item.posterLink} alt="movie" />
```

2022-07-04 21:47 UTC, kathrynowy commented on src/components/Movie.jsx
> +        <Button buttonFir={item.eventId} />
fir?

2022-07-04 21:47 UTC, kathrynowy commented on src/components/Movie.jsx
> +    <div >
why do you need 2 divs?

2022-07-04 21:47 UTC, kathrynowy commented on src/components/Movie.jsx
> +  return (
```suggestion
  const { item } = props;
  
  return (
```

2022-07-04 21:47 UTC, kathrynowy commented on src/components/button.jsx
> +}
const
explicit return
identation (исправить оформление везде)

2022-07-04 21:47 UTC, kathrynowy commented on src/components/button.jsx
> +  const { buttonFir } = props;
fir?

2022-07-04 21:47 UTC, kathrynowy commented on src/components/disription.jsx
> +
do not leave empty line

2022-07-04 21:47 UTC, kathrynowy commented on src/components/disription.jsx
> +function Dicription() {
description
const

2022-07-04 21:47 UTC, kathrynowy commented on src/components/disription.jsx
> +  const [post, setPost] = useState([]);
why is the default value an array?

2022-07-04 21:47 UTC, kathrynowy commented on src/components/disription.jsx
> +  const [post, setPost] = useState([]);
the name should be 'movieDetails'

2022-07-04 21:47 UTC, kathrynowy commented on src/components/disription.jsx
> +    setPost(post)
```suggestion
    const data = await fetch(`https://soft.silverscreen.by:8443/wssite/webapi/event/data?filter=%7B%22event%22:%22${eventId}%22,%22city%22:%221%22%7D&extended=true  `);
    
    const posts = await data.json();
    
    setPost(posts[0])
```

2022-07-04 21:47 UTC, kathrynowy commented on src/components/disription.jsx
> +  const fetchItem = async () => {
useCallback

2022-07-04 21:47 UTC, kathrynowy commented on src/components/disription.jsx
> +    <div className="movieDetails"  >
```suggestion
    <div className="movieDetails">
```
?

2022-07-04 21:47 UTC, kathrynowy commented on src/components/disription.jsx
> +
?

2022-07-04 21:47 UTC, kathrynowy commented on src/components/disription.jsx
> +      <h1>"{post.name}"</h1>
use destructure 
const { name, annotation, etc... } = post;

2022-07-04 21:47 UTC, kathrynowy commented on src/components/disription.jsx
> +      <img src={post.posterLink} alt="movie"></img>
```suggestion
      <img src={post.posterLink} alt="movie" />
```

2022-07-04 21:47 UTC, kathrynowy commented on src/components/films.jsx
> +  const [items, setItems] = useState([]);
add changes as before here

2022-07-08 19:04 UTC, Anastasiya-Shir commented on src/App.css
> +}
fixed

2022-07-08 19:04 UTC, Anastasiya-Shir commented on src/App.css
> +  padding:3% 10%;
fixed

2022-07-08 19:05 UTC, Anastasiya-Shir commented on src/App.css
> + .header{
fixed

2022-07-08 19:05 UTC, Anastasiya-Shir commented on src/App.css
> +  background-color: aqua;
fixed

2022-07-08 19:06 UTC, Anastasiya-Shir commented on src/components/disription.jsx
> +    <div className="movieDetails"  >
fixed

2022-07-08 19:06 UTC, Anastasiya-Shir commented on src/components/disription.jsx
> +
fixed

2022-07-08 19:07 UTC, Anastasiya-Shir commented on src/components/disription.jsx
> +      <img src={post.posterLink} alt="movie"></img>
fixed

2022-07-08 19:15 UTC, Anastasiya-Shir commented on src/components/disription.jsx
> +      <h1>"{post.name}"</h1>
fixed

2022-07-10 09:32 UTC, kathrynowy requested changes

2022-07-10 09:32 UTC, kathrynowy commented on src/components/Movie.jsx
> +  const [scroll, setScroll] = useState(0);
```suggestion
  const { item } = props;
  
  const [scroll, setScroll] = useState(0);
```

2022-07-10 09:32 UTC, kathrynowy commented on src/components/Movie.jsx
> +  const handleButton = () => {
which button?

2022-07-10 09:32 UTC, kathrynowy commented on src/components/Movie.jsx
> +    return () => window.removeEventListener("scroll", handleScroll);
```suggestion
    window.addEventListener("scroll", handleScroll);
    
    return () => window.removeEventListener("scroll", handleScroll);
```

2022-07-10 09:32 UTC, kathrynowy commented on src/components/Notfoundpage.jsx
> +      <h1>404 not wound, we have no such page </h1></div>)
оформление

2022-07-10 09:32 UTC, kathrynowy commented on src/components/Notfoundpage.jsx
> +export default Notfounpage;
CamelCase

2022-07-10 09:32 UTC, kathrynowy commented on src/components/Notfoundpage.jsx
> +  return (
const

2022-07-10 09:32 UTC, kathrynowy commented on src/components/button.jsx
> +  return (<Link to={`/movie-description/${buttonFir}`}> Buy </Link>)
explicit return

2022-07-10 09:32 UTC, kathrynowy commented on src/components/disription.jsx
> +    setPost(post);
```suggestion
    const posts = await data.json();

    setPost(posts[0]);
```

2022-07-10 09:32 UTC, kathrynowy commented on src/components/disription.jsx
> +    <div className="movieDetails">
```suggestion
    <div className="movie-details">
```

2022-07-10 09:32 UTC, kathrynowy commented on src/components/disription.jsx
> +
empty line

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +
?

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +      setValue(1);
which value?

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +    }
```suggestion
    if (event.target.value === "Минск") {
      setValue(1);

      return setValue(1);
    } else {

      return (setValue(5))
    }
```

зачем здесь return?
переписать в 1 строчку

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +  function changeSelect(event) {
const!

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +      // const item = [];
?

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +      setItems(item);
setItemSSSS? 
и сетаешь туда item
переназывай

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +        setEmpty(true);
зачем это состояние?

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +        setEmpty(true);
зачем проверять на 0??

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +      if (item.length === 0) {
```suggestion
      if (!item.length) {
```

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +      if (item.length > 1 && item.length < 20) {
?

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +
убрать пустую строку

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +      {isError
вынеси тоже наверх, как сделала с isLoading

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +            ? (<div>Movies are Loading</div>)
у тебя это не сработает же

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +            ? (<div>Movies are Loading</div>)
и кучу таких тернарников мы не пишем

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +              isEmpty ?
убрать это состояние isEmpty
это легко проверить итак

2022-07-10 09:32 UTC, kathrynowy commented on src/components/films.jsx
> +export default Films;
movies everywhere!

2022-07-10 09:32 UTC, kathrynowy commented on src/components/header.js
> +  // function showForm(){
?

2022-07-17 14:29 UTC, Anastasiya-Shir commented on src/App.css
> +.App {
fixed

2022-07-22 05:02 UTC, kathrynowy requested changes

2022-07-22 05:02 UTC, kathrynowy commented on src/App.css
> +.goUp {
```suggestion
.go-up {
```

2022-07-22 05:02 UTC, kathrynowy commented on src/App.css
> +.noErrorMessege{
change classes to -

2022-07-22 05:02 UTC, kathrynowy commented on src/App.css
> +  color: #ff0000;
colors to the scss file "variables" and import (use sass colors)

2022-07-22 05:02 UTC, kathrynowy commented on src/App.css
> +.activeButon:disabled{
button

2022-07-22 05:02 UTC, kathrynowy commented on src/App.js
> +}
```suggestion
  return (
    <>
   <Router>
      <div className="app">
        <Header setOpen={setOpen} />
        
        <Routes>
          <Route exact path="/" element={<Movies />} />
          <Route path="/movie-description/:eventId" element={<Dicription />} />
          <Route path="*" element={<NotFoundPage />} />
        </Routes>
      </div>
    </Router>
    
      <BasicModal open={open} setOpen={setOpen} />
      </>
  );
}
```

2022-07-22 05:02 UTC, kathrynowy commented on src/App.js
> +        <Header setOpen={setOpen} />
setOpen what?

2022-07-22 05:02 UTC, kathrynowy commented on src/App.js
> +  const [open, setOpen] = React.useState(false);
remove Ract.

2022-07-22 05:02 UTC, kathrynowy commented on src/components/Modal.jsx
> +
?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/Modal.jsx
> +    return <ModalFirst open={open} setOpen={setOpen} formType={formType} setFormType={setFormType} />
don't name first second etc.

2022-07-22 05:02 UTC, kathrynowy commented on src/components/Modal.jsx
> +  const [formType, setFormType] = React.useState(false);
```suggestion
  const [formType, setFormType] = useState(false);
```

2022-07-22 05:02 UTC, kathrynowy commented on src/components/Modal.jsx
> +  const [formType, setFormType] = React.useState(false);
what does mean formType false?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +  const { setFormType } = props;
? in 1 line

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +export default function ModalFirst(props) {
const

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +  const { setFormType } = props;
? in 1 line

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +  const [buttonDisabled, setButtonDisabled] = useState(true)
separate

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +  const [errorMesege, SetErrorMessege] = useState(false);
why does it start with a capital letter?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +  function sigIn() {
sigNIn

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +  function sigIn() {
const

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +    if (searchUser() && searchUser().password == password) {
подумай сколько раз ты вызываешь функцию и сколько раз будет происходит в ней перебор find 

нужно вызвать 1 раз и везде использовать результат

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +    if (searchUser() && searchUser().password == password) {
===

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +      searchUser().isAuth = true;
опять вызываешь

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +      localStorage.setItem(" isUserAuthrized ", JSON.stringify([isUserAuthrized]));
почему пробелы?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +      localStorage.setItem(" isUserAuthrized ", JSON.stringify([isUserAuthrized]));
зачем здесь массив?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +      console.log({ users })
зачем здесь обьект в логе?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +    } else alert("Check you password or email")
всегда пишем {}

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +  }
getIsBtnDisabled 
и какая btn?

плюс написать в 1 строчку

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +  }
а еще вдруг password / email будут undefined?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +                SetErrorMessege(true)
что я говорила про инлайн функции?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +  }
а еще вдруг password / email будут undefined?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +              onChange={(e) => { setPVavue(e.target.value); console.log(password); getbuttonDisabled() }}
тоже самое
все инлайн функции убрать

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +            <p className={errorMesege ? 'errorMessege' : "noErrorMessege"} >Неккорерктно введен email</p>
все сообщения на англ

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModalSign.jsx
> +          <a onClick={function () {
same

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +const style = {
одни и те же стили

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +  const [phonemail, setPhonemail] = useState("");
почему в конце email?))

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +  const { setFormType } = props
1 line

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +  const [buttonDisabled, setButtonDisabled] = useState(true)
if we have a boolean variable - we name it isNounAdjective

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +  const [password, setpassword] = useState("");
раздели все стейты

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +  const [errorMesege, SetErrorMessege] = useState(false);
capital letter

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +  const validateEmail = (email) => {
эта функция используется не первый раз
стразу выноси в папку utils

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +  const getbuttonDisabled = () => {
getIsBtnDisabled

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +    if (firstNamemail.length > 0 && lastNamemail.length > 0 && phonemail.length > 0 && repeatpassword.length > 0 && password.length > 0 && email.length > 0 && errorMesege === false) {
ты уверена, что тебе нужно проверять length > 0? если у тебя строка и там есть хоть 1 символ - это true , если нет  false


и переписать вот это errorMesege === false

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +    } else setButtonDisabled(true)
всегде {}

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +  }
how do we name functions?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +      SetErrorMessege(false);
in 1 line pls!!

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +  const searchsimpleUser = (users, newUser) => {
```suggestion
  const searchsimpleUser = (users, email) => {
```

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +    return users.find(item => item.email === newUser.email);
remove return 
```suggestion
    return users.find(item => item.email === email);
```

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +    setFormType(false)
? formtype false? what is it?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +            <input placeholder='Email' onChange={(e) => {
remove inline

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +                SetErrorMessege(false)
в 1 строчку

2022-07-22 05:02 UTC, kathrynowy commented on src/components/ModlSignUp.jsx
> +            <input placeholder='first Name' onChange={(e) => { setFirstNamemail(e.target.value); console.log(firstNamemail); getbuttonDisabled() }} style={{
тоже самое
и не вызывать самой getbuttonDisabled
а в useMemo написать
isBtnDisabled = useMemo. и там вычислять когда меняется переменная

2022-07-22 05:02 UTC, kathrynowy commented on src/components/Movies.jsx
> +                  {/* <button className={scroll < 300 ? 'goUp' : "show"} onClick={handleButton}> Go Up</button> */}
?

2022-07-22 05:02 UTC, kathrynowy commented on src/components/Movies.jsx
> +                :
use if above, it looks very vague

2022-07-22 05:02 UTC, kathrynowy commented on src/components/Movies.jsx
> +  const [isError, setError] = useState(false);
```suggestion
const Movies = () => {
  const [value, setValue] = useState(1);
  
  const [items, setItems] = useState([]);
  
  const [isLoading, setLoading] = useState(false);
  
  const [isEmpty, setEmpty] = useState(false);
  
  const [isError, setError] = useState(false);
```

2022-08-08 18:46 UTC, kathrynowy approved these changes

2022-08-08 18:46 UTC, kathrynowy commented on src/App.scss
> +$aquamarine:#7fffd4;
move to a separate file

2022-08-08 18:46 UTC, kathrynowy commented on src/App.scss
> +$aquamarine:#7fffd4;
src/styles/variables.scss

2022-08-08 18:46 UTC, kathrynowy commented on src/App.scss
> +  border: 2px solid $red;  border-radius: 50%;
?

2022-08-09 18:44 UTC, merged