redux
Anastasiya-Shir/AplicationReact pull request #2
Opened 2022-08-25 19:33 UTC by Anastasiya-Shir

2022-09-18 18:24 UTC, kathrynowy requested changes

2022-09-18 18:24 UTC, kathrynowy commented on src/App.js
>    const [open, setOpen] = useState(false);
isOpen - bool variable

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +  const { setOpen, items, setFindFilms } = props;
move destructuring to the top

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +  const [isUserAuthorized, setIsUserAuthorized] = useState("");
use only '' , not ""

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +    const emailJson = localStorage.getItem('isUserAuthrized');
remove logic with local storage

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +  let searchFilm = () => {
useCallback and const

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +      items.acronym.toUpperCase().includes(searchFilms[searchFilms.length - 1].searchFilms.toUpperCase()))
move this to useSelector

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +    dispatch(getFilm({ inputSearch }));
why do you pass an object here?

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +      <form onSubmit={e => e.preventDefault()}>
remove inline functions

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +        <input type="search" onChange={function (e) {
same here

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +        ? <button type="button" onClick={function () { setOpen(true) }}> Sign in  </button>
remove inline function everywhere and write me in TG why is it bad to write inline funcs

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +  const item = useSelector(state => state.AddMovies.films)
write useSelectors properly
and we don't name field with a capital letter AddMovies - addMovies

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +      return setValue(1);
?

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +      return (setValue(5))
you don't need to write return here

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +  }, [value]);
why do you need value here?

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +
no need to paste an empty line

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +                <option>Гродно</option>
remove ternaries and move above with if else

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +              {findFilms.length > 0 ? findFilms.map((item) => <Movie key={item.eventId} item={item} />) : item.map((item) => <Movie key={item.eventId} item={item} />)}
remove it

always use filteredMovies
if the search is empty - add all movies to filtered

2022-09-18 18:24 UTC, kathrynowy commented on src/components/Movies/Movies.jsx
> +              {findFilms.length > 0 ? findFilms.map((item) => <Movie key={item.eventId} item={item} />) : item.map((item) => <Movie key={item.eventId} item={item} />)}
and we don't check for 0 like this

!findFilms.length

2022-09-18 18:24 UTC, kathrynowy commented on src/components/store/index.js
> +    AddMovies: toggleIsFetchingReducer,
be careful with naming

2022-09-18 18:24 UTC, kathrynowy commented on src/components/store/searchSlice/index.js
> +        searchFilms: action.payload.inputSearch,
searchQuery

2022-09-18 18:24 UTC, kathrynowy commented on src/components/store/thunk/LoadingMovieList.jsx
> +// }
?

2022-09-18 18:24 UTC, kathrynowy commented on src/components/store/thunk/LoadingMovieList.jsx
> +      const data = await fetch(`https://soft.silverscreen.by:8443/wssite/webapi/event/data?filter=%7B%22city%22:${value}%7D&extended=true`)
use axios

2022-09-18 18:24 UTC, kathrynowy commented on src/components/store/thunk/LoadingMovieList.jsx
> +  }
?

2022-09-18 18:24 UTC, kathrynowy commented on src/components/store/thunk/LoadingMovieList.jsx
> +  }
add eslint

2022-09-18 18:24 UTC, kathrynowy commented on src/service/use-debounce.jsx
> +      return () => {
?

2022-09-21 17:34 UTC, Anastasiya-Shir commented on src/components/Header/Header.jsx
> +  const { setOpen, items, setFindFilms } = props;
fixed

2022-10-11 07:21 UTC, kathrynowy requested changes

2022-10-11 07:21 UTC, kathrynowy commented on src/App.css
> +  color: #7fffd4;
move to variables sass

2022-10-11 07:21 UTC, kathrynowy commented on src/App.css
> +.Main {
we don't name classnames with the capital letter

2022-10-11 07:21 UTC, kathrynowy commented on src/App.css
> +  flex-direction: row;
it's a default value

2022-10-11 07:21 UTC, kathrynowy commented on src/App.css
> +}/*# sourceMappingURL=App.css.map */
?

2022-10-11 07:21 UTC, kathrynowy commented on src/App.js
>    const [open, setOpen] = useState(false);
isOpen

2022-10-11 07:21 UTC, kathrynowy commented on src/App.js
>  import { BrowserRouter as Router, Routes, Route, } from 'react-router-dom';
change order of imports pls
as i mentioned on a call

2022-10-11 07:21 UTC, kathrynowy commented on src/App.scss
> +.logoSearch{
class-name-we-write-like-this
don't forget pls

2022-10-11 07:21 UTC, kathrynowy commented on src/components/AlertSigIn/AlertSigIn.jsx
> +
.

2022-10-11 07:21 UTC, kathrynowy commented on src/components/AlertSigIn/AlertSigIn.jsx
> +
1 определись как ты делаешь экспорты компонентов, везде по-разному
2 ненужная пустая строка поле открытия компонента/функции И так далее

2022-10-11 07:21 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +  const dispatch = useDispatch();
вынести в стор в файл selectors как я показывала

2022-10-11 07:21 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +  function Def(e) {
def?

2022-10-11 07:21 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +  }
почему не стрелочная?
название handleSearch

2022-10-11 07:21 UTC, kathrynowy commented on src/components/Header/Header.jsx
> +    dispatch(getFilm({ inputSearch }));
зачем переменная setInputSearch

2022-11-07 13:38 UTC, closed without merging